name: Flutter CI

# Trigger the workflow on push to the master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    # Use the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v2

      # Step 2: Set up the Java environment
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # Use a stable JDK distribution like Zulu or AdoptOpenJDK
          java-version: '11' # Java 11 is recommended for Android builds

      # Step 3: Set up Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta' # Specify the flutter channel (beta, dev, or stable)

      # Step 4: Get Flutter
