# Build Share Plus Example
name: share_plus

concurrency:
  group: share_plus_${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
      - main

  pull_request:
    paths:
      - "packages/share_plus/**"
      - ".github/workflows/share_plus.yaml"
      - "!**.md"
      - "!**.gitignore"

env:
  PLUGIN_SCOPE: "*share_plus*"
  PLUGIN_EXAMPLE_SCOPE: "*share_plus_example*"

jobs:
  analyze:
    name: "Dart Analyzer"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
      - name: "Bootstrap Workspace"
        run: melos bootstrap

  android_build:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh android ./lib/main.dart
      # Upload the APK as an artifact
      - name: "Upload APK"
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: ./build/app/outputs/apk/release/app-release.apk
      
